// <auto-generated />
using System;
using CarRentalApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRentalApp.Migrations
{
    [DbContext(typeof(CarRentalContext))]
    [Migration("20190725155129_jebiga2")]
    partial class jebiga2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarRentalApp.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int>("CarCategoryId");

                    b.Property<string>("Color");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("Mileage");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedAt");

                    b.Property<int>("ProductionYear");

                    b.HasKey("Id");

                    b.HasIndex("CarCategoryId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Audi",
                            CarCategoryId = 4,
                            Color = "Black",
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 302, DateTimeKind.Utc).AddTicks(6001),
                            Mileage = 10500,
                            Model = "A4",
                            ProductionYear = 2018
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BMW",
                            CarCategoryId = 3,
                            Color = "Red",
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 302, DateTimeKind.Utc).AddTicks(8033),
                            Mileage = 100500,
                            Model = "320d",
                            ProductionYear = 2015
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Mazda",
                            CarCategoryId = 3,
                            Color = "Black",
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 302, DateTimeKind.Utc).AddTicks(8061),
                            Mileage = 12500,
                            Model = "3",
                            ProductionYear = 2014
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Audi",
                            CarCategoryId = 4,
                            Color = "Blue",
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 302, DateTimeKind.Utc).AddTicks(8061),
                            Mileage = 25500,
                            Model = "A7",
                            ProductionYear = 2018
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Mercedes",
                            CarCategoryId = 3,
                            Color = "Black",
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 302, DateTimeKind.Utc).AddTicks(8061),
                            Mileage = 150000,
                            Model = "c200",
                            ProductionYear = 2013
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Citroen",
                            CarCategoryId = 4,
                            Color = "Yellow",
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 302, DateTimeKind.Utc).AddTicks(8061),
                            Mileage = 107500,
                            Model = "c3",
                            ProductionYear = 2010
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Peugeot",
                            CarCategoryId = 3,
                            Color = "Red",
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 302, DateTimeKind.Utc).AddTicks(8061),
                            Mileage = 100500,
                            Model = "307",
                            ProductionYear = 2015
                        });
                });

            modelBuilder.Entity("CarRentalApp.Models.CarCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("ModifiedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CarCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 304, DateTimeKind.Utc).AddTicks(3159),
                            Name = "van"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 304, DateTimeKind.Utc).AddTicks(3489),
                            Name = "mini-van"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 304, DateTimeKind.Utc).AddTicks(3495),
                            Name = "limousine"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 304, DateTimeKind.Utc).AddTicks(3495),
                            Name = "hatchback"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 304, DateTimeKind.Utc).AddTicks(3495),
                            Name = "coupe"
                        });
                });

            modelBuilder.Entity("CarRentalApp.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("ModifiedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Zip")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 304, DateTimeKind.Utc).AddTicks(9588),
                            Name = "Sisak",
                            Zip = "44000"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(151),
                            Name = "Zagreb",
                            Zip = "10000"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(162),
                            Name = "Velika Gorica",
                            Zip = "10410"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(162),
                            Name = "Osijek",
                            Zip = "31000"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(162),
                            Name = "Slavonski Brod",
                            Zip = "35000"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(162),
                            Name = "Rijeka",
                            Zip = "51000"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(162),
                            Name = "Varaždin",
                            Zip = "42000"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(162),
                            Name = "Krapina",
                            Zip = "49000"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(162),
                            Name = "Split",
                            Zip = "21000"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(168),
                            Name = "Dubrovnik",
                            Zip = "20000"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(168),
                            Name = "Trogir",
                            Zip = "21220"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(168),
                            Name = "Šibenik",
                            Zip = "22000"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(174),
                            Name = "Vukovar",
                            Zip = "32000"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(174),
                            Name = "Vinkovci",
                            Zip = "37000"
                        });
                });

            modelBuilder.Entity("CarRentalApp.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("DrivingLicenceNumber")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ModifiedAt");

                    b.HasKey("Id");

                    b.HasIndex("DrivingLicenceNumber")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(6983),
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "11111111",
                            FirstName = "Ivan",
                            LastName = "Ivanovic"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(8155),
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "22222222",
                            FirstName = "Marko",
                            LastName = "Marković"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(8167),
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "33333333",
                            FirstName = "Josip",
                            LastName = "Josipović"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(8172),
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "44444444",
                            FirstName = "Pero",
                            LastName = "Perić"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(8172),
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "55555555",
                            FirstName = "Matko",
                            LastName = "Matković"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(8172),
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "88888888",
                            FirstName = "Ivica",
                            LastName = "Ivić"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(8172),
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "99999999",
                            FirstName = "Davor",
                            LastName = "Davorić"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(8172),
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "12121212",
                            FirstName = "Dario",
                            LastName = "Dariović"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 305, DateTimeKind.Utc).AddTicks(8172),
                            DateOfBirth = new DateTime(1990, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DrivingLicenceNumber = "12312312",
                            FirstName = "Dorian",
                            LastName = "Dorianović"
                        });
                });

            modelBuilder.Entity("CarRentalApp.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime?>("ModifiedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 306, DateTimeKind.Utc).AddTicks(2183),
                            Name = "Vukovarska 4c"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 306, DateTimeKind.Utc).AddTicks(2740),
                            Name = "Zagrebačka 5"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 4,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 306, DateTimeKind.Utc).AddTicks(2746),
                            Name = "Petrova 5"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 306, DateTimeKind.Utc).AddTicks(2746),
                            Name = "Sisačka 13"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 7,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 306, DateTimeKind.Utc).AddTicks(2746),
                            Name = "Slavonska 4c"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 8,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 306, DateTimeKind.Utc).AddTicks(2752),
                            Name = "Petrinjska 4c"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 1,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 306, DateTimeKind.Utc).AddTicks(2752),
                            Name = "Vukovarska 15c"
                        });
                });

            modelBuilder.Entity("CarRentalApp.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("CustomerId");

                    b.Property<int>("DropOffLocationId");

                    b.Property<DateTime>("EndDate");

                    b.Property<DateTime?>("ModifiedAt");

                    b.Property<int>("PickUpLocationId");

                    b.Property<string>("Remarks");

                    b.Property<bool>("Reserved");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DropOffLocationId");

                    b.HasIndex("PickUpLocationId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 3,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 307, DateTimeKind.Utc).AddTicks(381),
                            CustomerId = 3,
                            DropOffLocationId = 3,
                            EndDate = new DateTime(2015, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PickUpLocationId = 2,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2015, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CarId = 3,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 307, DateTimeKind.Utc).AddTicks(2224),
                            CustomerId = 5,
                            DropOffLocationId = 4,
                            EndDate = new DateTime(2016, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PickUpLocationId = 1,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2016, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CarId = 1,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 307, DateTimeKind.Utc).AddTicks(2247),
                            CustomerId = 6,
                            DropOffLocationId = 3,
                            EndDate = new DateTime(2018, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PickUpLocationId = 1,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2018, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CarId = 2,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 307, DateTimeKind.Utc).AddTicks(2252),
                            CustomerId = 2,
                            DropOffLocationId = 2,
                            EndDate = new DateTime(2019, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PickUpLocationId = 1,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2019, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CarId = 6,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 307, DateTimeKind.Utc).AddTicks(2252),
                            CustomerId = 2,
                            DropOffLocationId = 2,
                            EndDate = new DateTime(2019, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PickUpLocationId = 1,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2019, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CarId = 5,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 307, DateTimeKind.Utc).AddTicks(2252),
                            CustomerId = 2,
                            DropOffLocationId = 2,
                            EndDate = new DateTime(2019, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PickUpLocationId = 1,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2019, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CarId = 4,
                            CreatedAt = new DateTime(2019, 7, 25, 15, 51, 29, 307, DateTimeKind.Utc).AddTicks(2252),
                            CustomerId = 2,
                            DropOffLocationId = 2,
                            EndDate = new DateTime(2019, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PickUpLocationId = 1,
                            Remarks = "blah blah",
                            Reserved = true,
                            StartDate = new DateTime(2019, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CarRentalApp.Models.Car", b =>
                {
                    b.HasOne("CarRentalApp.Models.CarCategory", "CarCategory")
                        .WithMany()
                        .HasForeignKey("CarCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CarRentalApp.Models.Location", b =>
                {
                    b.HasOne("CarRentalApp.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CarRentalApp.Models.Rental", b =>
                {
                    b.HasOne("CarRentalApp.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarRentalApp.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarRentalApp.Models.Location", "DropOffLocation")
                        .WithMany()
                        .HasForeignKey("DropOffLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarRentalApp.Models.Location", "PickUpLocation")
                        .WithMany()
                        .HasForeignKey("PickUpLocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
